//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CJ()
        {
            this.Cidades = new HashSet<Cidade>();
        }
    
        public int CjId { get; set; }
        public int RajId { get; set; }
        public int CjIdent { get; set; }
        public string CjNome { get; set; }
        public Nullable<bool> IsExcluido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cidade> Cidades { get; set; }
        public virtual RAJ RAJ { get; set; }
    }
}
