//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPDEData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public System.DateTime Data { get; set; }
        public string Usuario { get; set; }
        public string Maquina { get; set; }
        public string Version { get; set; }
        public string MethodTitle { get; set; }
        public string Message { get; set; }
    }
}
